### ISSUE TITLE
Add ability to control tab-size

### ISSUE THREAD

**Issue by gabrielflorit** [zlsa/indoc#15]
For some inexplicable reason browsers render `pre` tab sizes with 8 spaces (8!). I'd personally like to set this to 2, e.g.

```css
pre {
  -moz-tab-size: 2;
  tab-size: 2;
}
```

but I'm sure others will prefer 4. What do you think is the best way to handle this? User config in `indoc.json`?
